name: Latest blog post
on:
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch:
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: gautamkrishnar/blog-post-workflow@master
              with:
                    max_post_count: "5"
                    feed_list: "https://ja-errorpro.cf/posts/index.xml"
                    template: '<tr><td><a href="https://ja-errorpro.cf$url">$title</a></td></tr>'